# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test and Build with Gradle

on:
  push:
    branches: [main, "feature/**"]
  pull_request:
    branches: [main, "feature/**"]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: cab302
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Run Migration Script
        run: export PGPASSWORD=postgres && psql postgres -h 127.0.0.1 -d cab302 -f ./migrations/v1/v1_setup_tables_and_enums.sql
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: "15"
          distribution: "adopt"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build & Test with Gradle
        run: ./gradlew build --stacktrace
